// <auto-generated />
using System;
using HITSBackEnd.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HITSBackEnd.Migrations.AddressesDb
{
    [DbContext(typeof(AddressesDbContext))]
    [Migration("20231105142037_AddAddressesDbToPorject")]
    partial class AddAddressesDbToPorject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HITSBackEnd.Models.AddressModels.AsAddrObject", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<int>("isActive")
                        .HasColumnType("integer")
                        .HasColumnName("isactive");

                    b.Property<int>("isActual")
                        .HasColumnType("integer")
                        .HasColumnName("isactual");

                    b.Property<string>("level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("objectGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("objectguid");

                    b.Property<long>("objectId")
                        .HasColumnType("bigint")
                        .HasColumnName("objectid");

                    b.Property<string>("typename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("typename");

                    b.HasKey("id");

                    b.ToTable("AsAddrObjects");
                });

            modelBuilder.Entity("HITSBackEnd.Models.AddressModels.AsAdmHierarchy", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<int>("isActive")
                        .HasColumnType("integer")
                        .HasColumnName("isactive");

                    b.Property<long>("objectId")
                        .HasColumnType("bigint")
                        .HasColumnName("objectid");

                    b.Property<long>("parentObjId")
                        .HasColumnType("bigint")
                        .HasColumnName("parentobjId");

                    b.HasKey("id");

                    b.ToTable("AsAdmHierarchy");
                });

            modelBuilder.Entity("HITSBackEnd.Models.AddressModels.AsHouses", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("houseNum")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("housenum");

                    b.Property<int>("houseType")
                        .HasColumnType("integer")
                        .HasColumnName("housetype");

                    b.Property<int>("isActive")
                        .HasColumnType("integer")
                        .HasColumnName("isactive");

                    b.Property<int>("isActual")
                        .HasColumnType("integer")
                        .HasColumnName("isactual");

                    b.Property<Guid>("objectGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("objectguid");

                    b.Property<long>("objectId")
                        .HasColumnType("bigint")
                        .HasColumnName("objectid");

                    b.HasKey("id");

                    b.ToTable("AsHouses");
                });
#pragma warning restore 612, 618
        }
    }
}
